Lesson 37 finished
gloomy-onion/spa-first-project pull request #3
Opened 2022-08-23 15:47 UTC by gloomy-onion

2022-08-23 16:19 UTC, Alterqq requested changes

2022-08-23 16:19 UTC, Alterqq commented on src/components/Updates/Updates.jsx
>      let addPost = () => {
При создании функции мы используем const, потому что функция не изменяет значения

2022-08-23 16:19 UTC, Alterqq commented on src/components/Updates/Updates.jsx
> +    let onPostChange = () => {
Тут тоже

2022-08-23 16:19 UTC, Alterqq commented on src/components/redux/state.js
> -let rerenderEntireTree = () => {
const

2022-08-23 16:19 UTC, Alterqq commented on src/components/redux/state.js
> +        console.log('State changed.');
Лишний лог

2022-08-23 16:19 UTC, Alterqq commented on src/components/redux/state.js
> +    getState() {
отступ между методами для читемости

2022-08-24 10:42 UTC, gloomy-onion commented on src/components/redux/state.js
> +    getState() {
хорошо

2022-08-24 16:05 UTC, Alterqq approved these changes

2022-08-24 16:06 UTC, Alterqq commented
можем мержить

2022-08-24 16:29 UTC, merged